[package]
name = "parser"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "wasmfile"
path = "parser/lib.rs"

[dependencies]
wasm-bindgen = "0.2.74"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.117"
